# Generated by Django 5.1.3 on 2024-12-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='avg_churn_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
